# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

# need this explicitly
# for naming convention
before_deploy:
  - R CMD INSTALL --build ${PKG_TARBALL}
  # so no overwrite of linux build
  - if [ "$TRAVIS_OS_NAME" == "osx" ];
    then
    rm -f *.tar.gz
    fi